layout_spectrum: 0.5489739
typography_spectrum: 0.6815075
color:
  saturation: 0.4146455
  lightness: 0.1245336
  brandStrength: 0.4785448
  brandColors:
    - '#EFEFE5'
    - '#23061A'
    - '#C46235'
    - '#679974'
    - '#C6192D'
  rhythmicContrast: 0.5233209
name: DCOffline
